{{- if .Values.networkPolicy.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkguard-chart.labels" . | nindent 4 }}

spec:
  podSelector:
    matchLabels:
      app: redis

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: linkguard-chart
      ports:
        - protocol: TCP
          port: {{ .Values.redis.service.port }}

{{- end }}