{{- if not .Values.secret.existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkguard-chart.fullname" . }}
  labels:
    {{- include "linkguard-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEYS: {{ .Values.secret.apiKeys | quote }}

{{- end }}